name: CI

on:
  workflow_dispatch:
    inputs:
      signBinaries:
        description: "Upload binaries to SignPath"
        required: true
        type: boolean
        default: false
      signingPolicy:
        description: "Signing policy slug: test-signing or release-signing"
        required: true
        type: string
        default: test-signing
      publishBinaries:
        description: "Publish binaries to https://dl.glasgow-embedded.*/"
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: nixos-latest
    steps:
      - name: Install dependencies
        run: |
          cat >/etc/nix/nix.conf <<EOF
          experimental-features = flakes nix-command

          cores = 0
          max-jobs = auto
          EOF

          nix profile add nixpkgs#{coreutils-full,gnused,nodejs,zip}
      - name: Check out source code
        uses: https://code.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build MSI installers
        run: |
          nix build .#glasgow-installers --accept-flake-config --print-build-logs
          zip -j GlasgowInterfaceExplorer.zip result/*.msi
      - name: Upload to Forgejo
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: msi-installer-unsigned
          path: GlasgowInterfaceExplorer.zip
          retention-days: 1
          compression-level: 0
      - if: ${{ forgejo.event.inputs.signBinaries == 'true' }}
        name: Upload to SignPath
        run: |
          curl -D response.txt \
            -H "Authorization: Bearer ${{ secrets.SIGNPATH_TOKEN }}" \
            -F "projectSlug=glasgow" \
            -F "signingPolicySlug=${{ forgejo.event.inputs.signingPolicy }}" \
            -F "artifactConfigurationSlug=Windows_MSI" \
            -F "artifact=@GlasgowInterfaceExplorer.zip" \
            -F "parameters.repositoryUrl=${{ forgejo.server_url }}/${{ forgejo.repository }}" \
            -F "parameters.repositoryBranchName=${{ forgejo.ref_name }}" \
            -F "parameters.repositoryCommitId=${{ forgejo.sha }}" \
            -F "parameters.productVersion=0.1" \
            https://app.signpath.io/API/v1/${{ vars.SIGNPATH_ORG }}/SigningRequests/SubmitWithArtifact
          signingRequestId=$(sed <response.txt 's,\r,,' | grep -oP 'Location: \K.+')
          echo "signingRequestId=${signingRequestId}" >>"$GITHUB_OUTPUT"
      - if: ${{ forgejo.event.inputs.publishBinaries == 'true' }}
        name: Download git-pages-cli
        run: |
          curl -O https://codeberg.org/git-pages/git-pages-cli/releases/download/v1.10.1/git-pages-cli.linux-amd64
          sha256sum -c <<<"82fbb45e67a5feb570ae323cd4959d9c47987813290728dfa8a32c62d6510766  git-pages-cli.linux-amd64"
          mv git-pages-cli.linux-amd64 git-pages-cli
          chmod +x git-pages-cli
      - if: ${{ forgejo.event.inputs.publishBinaries == 'true' }}
        name: Upload to https://dl.glasgow-embedded.*/
        run: |
          ./git-pages-cli https://dl.glasgow-embedded.org/ --token ${{ forgejo.token }} --upload-dir result
          ./git-pages-cli https://dl.glasgow-embedded.cn/  --token ${{ forgejo.token }} --upload-dir result
